---
- hosts: ansible-tar1
  become: yes
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

    - name: "Install Apache, MySQL, PHP, and other dependencies."
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - ufw
        - python3-pymysql
        - apache2
        - apache2-utils
        - php7.4
        - php7.4-mysql
        - php7.4-cli
        - php7.4-cgi
        - php7.4-gd
        - libapache2-mod-php7.4
        - mariadb-server
        - mariadb-client

    - name: Install PHP Extensions
      apt: name={{ item }} update_cache=yes state=latest
      loop: "{{ php_modules }}"
      tags: [ system ]

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'

    - name: Set up Apache VirtualHost
      template:
        src: "files/apache.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Enable rewrite module
      shell: /usr/sbin/a2enmod rewrite
      notify: Reload Apache

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Restart Apache

    - name: Set the root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Remove all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Remove the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"

    - name: Set ownership
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Set permissions for directories
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"
      tags: [ wordpress ]

    - name: Set permissions for files
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"
      tags: [ wordpress ]

    - name: Set up Apache ports conf
      template:
        src: "files/apache-ports"
        dest: "/etc/apache2/ports.conf"
      notify: Reload Apache

    - name: Install NGINX
      apt: name=nginx update_cache=yes state=latest

    - name: Disable NGINX deafult config
      command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/.default

    - name: Set up NGINX VirtualHost
      template:
        src: "files/nginx.conf"
        dest: "/etc/nginx/sites-available/nginx"
      notify: Reload NGINX

    - name: Set up Apache VirtualHost
      template:
        src: "files/nginx.conf"
        dest: "/etc/nginx/sites-enabled/nginx"
      notify: Reload NGINX

#    - name: Set up wp-config
#      command: wordpress/* /var/www/{{ http_host }}/"

#    - name: Set permissions for directories
#      shell: "/usr/bin/find /var/www/{{ http_host }} -type d -exec chmod -R 755 {} \\;"

#    - name: Set permissions for files
#      shell: "/usr/bin/find /var/www/{{ http_host }} -type d -exec chown -R www-data:www-data {} \\;"

    - name: Set up wp-config
      template:
        src: "files/wp-config"
        dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"



  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded
